import "./globals.css";
import Nav from "./nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-4 min-h-[100vh] relative bg-gradient-to-br from-[#E8F0FE] to-[#E8F0FE] via-[#98b5ea]">
        <Nav
          endpoints={["About", "Methods", "Testamonials", "Contact", "Team"]}
        />
        {children}
        <footer className="">
          <p>feeter</p>
        </footer>
      </body>
    </html>
  );
}
