import "./globals.css";
import Nav from "./nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-4 min-h-[100vh] bg-gradient-to-br from-sky-500 to-indigo-500">
        <Nav endpoints={["About", "Methods", "Testamonials", "Contact Us"]} />
        {children}
      </body>
    </html>
  );
}
